# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' caculate **snowfall**
#' @name atmosSnow
#' @inheritParams all_vari
#' @return atmos_snow_mm (mm/m2/TS) snowfall volum
#' @param param_atmos_thr_Ts <-1, 3> (Cel) threshold air temperature that snow, parameter for [atmosSnow_ThresholdT()]
#' @export
atmosSnow_ThresholdT <- function(atmos_precipitation_mm, atmos_temperature_Cel, param_atmos_thr_Ts) {
    .Call(`_EDCHM_atmosSnow_ThresholdT`, atmos_precipitation_mm, atmos_temperature_Cel, param_atmos_thr_Ts)
}

#' @rdname atmosSnow
#' @param param_atmos_ubc_A0FORM <0.01, 3> (Cel) threshold air temperature that snow, it can not equal or small than 0, parameter for [atmosSnow_UBC()]
#' @export
atmosSnow_UBC <- function(atmos_precipitation_mm, atmos_temperature_Cel, param_atmos_ubc_A0FORM) {
    .Call(`_EDCHM_atmosSnow_UBC`, atmos_precipitation_mm, atmos_temperature_Cel, param_atmos_ubc_A0FORM)
}

#' **baseflow**
#' @name baseflow
#' @inheritParams all_vari
#' @return ground_baseflow_mm (mm/m2/TS) 
#' @param param_baseflow_sup_k <0.01, 1> coefficient parameter for [baseflow_SupplyPow()]
#' @param param_baseflow_sup_gamma <0.1, 5> exponential parameter for [baseflow_SupplyPow()]
#' @export
baseflow_SupplyPow <- function(ground_water_mm, ground_capacity_mm, param_baseflow_sup_k, param_baseflow_sup_gamma) {
    .Call(`_EDCHM_baseflow_SupplyPow`, ground_water_mm, ground_capacity_mm, param_baseflow_sup_k, param_baseflow_sup_gamma)
}

#' @rdname baseflow
#' @param param_baseflow_sur_k <0.01, 1> coefficient parameter for [baseflow_SupplyRatio()]
#' @export
baseflow_SupplyRatio <- function(ground_water_mm, param_baseflow_sur_k) {
    .Call(`_EDCHM_baseflow_SupplyRatio`, ground_water_mm, param_baseflow_sur_k)
}

#' @rdname baseflow
#' @export
baseflow_GR4J <- function(ground_water_mm, ground_capacity_mm) {
    .Call(`_EDCHM_baseflow_GR4J`, ground_water_mm, ground_capacity_mm)
}

#' @rdname baseflow
#' @param param_baseflow_grf_gamma <2, 7> exponential parameter for [baseflow_GR4Jfix()]
#' @export
baseflow_GR4Jfix <- function(ground_water_mm, ground_capacity_mm, param_baseflow_grf_gamma) {
    .Call(`_EDCHM_baseflow_GR4Jfix`, ground_water_mm, ground_capacity_mm, param_baseflow_grf_gamma)
}

#' **capilarise**
#' @name capirise
#' @inheritParams all_vari
#' @param param_capirise_sur_k <0.01, 1> coefficient parameter for[capirise_SupplyRatio()]
#' @return  ground_capillarise_mm (mm/m2/TS)
#' @export
capirise_SupplyRatio <- function(ground_water_mm, soil_water_mm, soil_capacity_mm, param_capirise_sur_k) {
    .Call(`_EDCHM_capirise_SupplyRatio`, ground_water_mm, soil_water_mm, soil_capacity_mm, param_capirise_sur_k)
}

#' @rdname capirise
#' @param param_capirise_sup_k <0.01, 1> coefficient parameter for [capirise_SupplyPow()]
#' @param param_capirise_sup_gamma <0.1, 5> exponential parameter for [capirise_SupplyPow()]
#' @export
capirise_SupplyPow <- function(ground_water_mm, soil_water_mm, soil_capacity_mm, param_capirise_sup_k, param_capirise_sup_gamma) {
    .Call(`_EDCHM_capirise_SupplyPow`, ground_water_mm, soil_water_mm, soil_capacity_mm, param_capirise_sup_k, param_capirise_sup_gamma)
}

#' @rdname capirise
#' @param param_capirise_acr_k <0.01, 1> coefficient parameter [capirise_AcceptRatio()]
#' @export
capirise_AcceptRatio <- function(ground_water_mm, soil_water_mm, soil_capacity_mm, param_capirise_acr_k) {
    .Call(`_EDCHM_capirise_AcceptRatio`, ground_water_mm, soil_water_mm, soil_capacity_mm, param_capirise_acr_k)
}

#' @rdname capirise
#' @param param_capirise_acp_k <0.01, 1> coefficient parameter for [capirise_AcceptPow()]
#' @param param_capirise_acp_gamma <0.1, 5> exponential parameter for [capirise_AcceptPow()]
#' @export
capirise_AcceptPow <- function(ground_water_mm, soil_water_mm, soil_capacity_mm, param_capirise_acp_k, param_capirise_acp_gamma) {
    .Call(`_EDCHM_capirise_AcceptPow`, ground_water_mm, soil_water_mm, soil_capacity_mm, param_capirise_acp_k, param_capirise_acp_gamma)
}

#' **confluence**
#' @description Routing methods with 
#' - `IUH`: IUH (Instant Unit Hydrograph) with one watercourse, 
#' - `IUH2S`; IUH with tweo watersource, those have the different IUH-vector, 
#' @inheritParams all_vari
#' @name confluen
#' @return confluenced water (mm/m2)
#' @export
confluen_IUH <- function(confluen_inputWater_mm, confluen_iuh_1) {
    .Call(`_EDCHM_confluen_IUH`, confluen_inputWater_mm, confluen_iuh_1)
}

#' @rdname confluen
#' @export
confluen_IUH2S <- function(land_runoff_mm, ground_baseflow_mm, confluen_iuhLand_1, confluen_iuhGround_1) {
    .Call(`_EDCHM_confluen_IUH2S`, land_runoff_mm, ground_baseflow_mm, confluen_iuhLand_1, confluen_iuhGround_1)
}

#' create **IUH** (Instant Unit Graphy)
#' @name confluenIUH
#' @inheritParams all_vari
#' @return IUH (list of num vector) 
#' @export
confluenIUH_GR4J1 <- function(confluen_responseTime_TS) {
    .Call(`_EDCHM_confluenIUH_GR4J1`, confluen_responseTime_TS)
}

#' @rdname confluenIUH
#' @export
confluenIUH_GR4J2 <- function(confluen_responseTime_TS) {
    .Call(`_EDCHM_confluenIUH_GR4J2`, confluen_responseTime_TS)
}

#' @rdname confluenIUH
#' @export
confluenIUH_Clark <- function(confluen_responseTime_TS) {
    .Call(`_EDCHM_confluenIUH_Clark`, confluen_responseTime_TS)
}

#' @rdname confluenIUH
#' @export
confluenIUH_Kelly <- function(confluen_responseTime_TS, confluen_concentratTime_TS) {
    .Call(`_EDCHM_confluenIUH_Kelly`, confluen_responseTime_TS, confluen_concentratTime_TS)
}

#' @rdname confluenIUH
#' @param param_confluen_nas_n parameters for[confluenIUH_Nash()]
#' @export
confluenIUH_Nash <- function(confluen_responseTime_TS, param_confluen_nas_n) {
    .Call(`_EDCHM_confluenIUH_Nash`, confluen_responseTime_TS, param_confluen_nas_n)
}

#' @rdname confluenIUH
#' @param param_confluen_nak_b,param_confluen_nak_n parameters for[confluenIUH_NashKumar()]
#' @export
confluenIUH_NashKumar <- function(param_confluen_nak_b, param_confluen_nak_n) {
    .Call(`_EDCHM_confluenIUH_NashKumar`, param_confluen_nak_b, param_confluen_nak_n)
}

#' **potential evapotranspiration**
#' @name evatransPotential
#' @description The concept potential ET estimate mainly the confluence from atmosphere, 
#' when the water in the ET-area is always enough. 
#' Actually we should also consider the charterers of the ET-area, there is free water area or vegetation or bar soil,
#' But we may don't have so many information and effective method, in order to get the truly potential ET.
#' So there is the simplified method: reference ET, it define the ET-area with some fest charterers, e.g. [evatransPotential_FAO56()].
#' In this situation we should give some factor for different ET-area.
#' @inheritParams all_vari
#' @details
#' - **_TurcWendling**: consider only the radiation and temperature as the main factors. 
#' \mjsdeqn{E_p = \frac{(100 R_s + 3.875 t_h k)\cdot(T + 22)}{150 (T + 123)}}
#' where
#'   - \mjseqn{E_p} is potential ET, `atmos_potentialEvatrans_mm`
#'   - \mjseqn{R_s} is solar radiation, `atmos_solarRadiat_MJ`
#'   - \mjseqn{t_h} is time step in hour, `time_step_h`
#'   - \mjseqn{T} is average air temperature, `atmos_temperature_Cel`
#'   - \mjseqn{k} is `param_evatrans_tur_k`
#' @param param_evatrans_tur_k <0.6, 1> parameter for [evatransPotential_TurcWendling()], higher value when closer to the sea
#' @return potential evapotranspiration (mm/m2)
#' @export
evatransPotential_TurcWendling <- function(atmos_temperature_Cel, atmos_solarRadiat_MJ, time_step_h, param_evatrans_tur_k) {
    .Call(`_EDCHM_evatransPotential_TurcWendling`, atmos_temperature_Cel, atmos_solarRadiat_MJ, time_step_h, param_evatrans_tur_k)
}

#' @rdname evatransPotential
#' @details
#' - **_Linacre**: consider only the temperature as the main factors. 
#' \mjsdeqn{E_p = \frac{\frac{100(0.75 - \alpha)(T + 0.006 z)}{100 - \phi} + 15(T - T_d)}{80 - T}}
#' \mjsdeqn{T_d = T - 20 (1-H_R)}
#' where
#'   - \mjseqn{\alpha} is albedo, `land_albedo_1`
#'   - \mjseqn{z} is elevation, `land_elevation_m`
#'   - \mjseqn{T_d} is dewpoint temperature,
#'   - \mjseqn{H_R} is relative humidity, `atmos_relativeHumidity_1`
#' @export
evatransPotential_Linacre <- function(time_dayOfYear_, atmos_temperature_Cel, atmos_relativeHumidity_1, land_latitude_Degree, land_elevation_m, land_albedo_1) {
    .Call(`_EDCHM_evatransPotential_Linacre`, time_dayOfYear_, atmos_temperature_Cel, atmos_relativeHumidity_1, land_latitude_Degree, land_elevation_m, land_albedo_1)
}

#' @rdname evatransPotential
#' @details
#' - **_FAO56**: consider not only radiation and temperature but also other variable like wind speed
#' as the main factors. 
#' \mjsdeqn{E_p =\frac{0.408 \Delta\left(R_n - G\right)+\gamma \frac{900}{T+273} {u}_{2}\left({e}_{{s}}-{e}_{{a}}\right)}{\Delta+\gamma\left(1+0.34 {u}_{2}\right)}}
#' where
#'   - \mjseqn{\Delta} is slope vapour pressure curve (kPa °C-1)
#'   - \mjseqn{R_n} is net radiation, `atmos_netRadiat_MJ`
#'   - \mjseqn{G} is soil heat flux density
#'   - \mjseqn{u_2} is wind speed at 2 m height, `atmos_windSpeed2m_m_s`
#'   - \mjseqn{e_s} is saturation vapour pressure, `atmos_saturatVaporPress_hPa`
#'   - \mjseqn{e_a} is actual vapour pressure, `atmos_vaporPress_hPa`
#'   - \mjseqn{\gamma} is psychrometric constant
#' @export
evatransPotential_FAO56 <- function(time_dayOfYear_, atmos_temperature_Cel, atmos_vaporPress_hPa, atmos_saturatVaporPress_hPa, atmos_netRadiat_MJ, atmos_windSpeed2m_m_s, land_latitude_Degree, land_elevation_m) {
    .Call(`_EDCHM_evatransPotential_FAO56`, time_dayOfYear_, atmos_temperature_Cel, atmos_vaporPress_hPa, atmos_saturatVaporPress_hPa, atmos_netRadiat_MJ, atmos_windSpeed2m_m_s, land_latitude_Degree, land_elevation_m)
}

#' **actuall evapotranspiration**
#' @name evatransActual
#' @inheritParams all_vari
#' @description
#' \loadmathjax
#' Under the concept of the conceptional HM, the actually ET is always consider as a part of potential ET:
#' \mjsdeqn{E_a = f E_p}
#' where
#' - \mjseqn{E_a} is `land_evatrans_mm` or `soil_evatrans_mm`
#' - \mjseqn{E_p} is `atmos_potentialEvatrans_mm`
#' - \mjseqn{f} is estimated ratio.
#' Then the different `evatransActual` methods will estimate the ratio \mjseqn{f}.
#' @return actually ET in (mm/m2/TS)
#' - evaporation in interception (landLy), `land_evatrans_mm`
#' - transpiration in root
#' - evaporation in soil (soilLy), `soil_evatrans_mm`
#' @details
#' - **_SupplyRatio**: the water content (the ratio to the maximal capacity) 
#' is considered as th main factors for the ratio \mjseqn{f}.
#' \mjsdeqn{f = k  \frac{W}{C}}
#' where
#'   - \mjseqn{W} is water volume in (mm/m2/TS), `water_mm`, `land_interceptWater_mm`, `soil_water_mm`
#'   - \mjseqn{C} is water capacity in (mm/m2), `capacity_mm`, `land_interceptCapacity_mm`, `soil_capacity_mm`
#'   - \mjseqn{k} is `param_evatrans_sur_k`
#' @param param_evatrans_sur_k <0.1, 1> parameter for [evatransActual_SupplyRatio()], ratio of potential ET, that is estimated as actually ET  
#' @export
evatransActual_SupplyRatio <- function(atmos_potentialEvatrans_mm, water_mm, capacity_mm, param_evatrans_sur_k) {
    .Call(`_EDCHM_evatransActual_SupplyRatio`, atmos_potentialEvatrans_mm, water_mm, capacity_mm, param_evatrans_sur_k)
}

#' @rdname evatransActual
#' @details
#' - **_SupplyPow**: the water content (the ratio to the maximal capacity) 
#' is considered as th main factors for the ratio \mjseqn{f}.
#' \mjsdeqn{f = k  \left(\frac{W}{C}\right)^\gamma}
#' where
#'   - \mjseqn{k} is `param_evatrans_sup_k`
#'   - \mjseqn{\gamma} is `param_evatrans_sup_gamma`
#' @param param_evatrans_sup_k <0.1, 1> parameter for [evatransActual_SupplyPow()], ratio of this method
#' @param param_evatrans_sup_gamma <-3, 5> parameter for [evatransActual_SupplyPow()], exponent of this method
#' @export
evatransActual_SupplyPow <- function(atmos_potentialEvatrans_mm, water_mm, capacity_mm, param_evatrans_sup_k, param_evatrans_sup_gamma) {
    .Call(`_EDCHM_evatransActual_SupplyPow`, atmos_potentialEvatrans_mm, water_mm, capacity_mm, param_evatrans_sup_k, param_evatrans_sup_gamma)
}

#' @rdname evatransActual
#' @details
#' - **_AcceptPow**: only the potential ET 
#' is considered as th main factors for the ratio \mjseqn{f}.
#' \mjsdeqn{f = k}
#' where
#'   - \mjseqn{k} is `param_evatrans_acr_k`
#' @param param_evatrans_acr_k <0.1, 1> parameter for [evatransActual_AcceptRatio()]
#' @export
evatransActual_AcceptRatio <- function(atmos_potentialEvatrans_mm, water_mm, param_evatrans_acr_k) {
    .Call(`_EDCHM_evatransActual_AcceptRatio`, atmos_potentialEvatrans_mm, water_mm, param_evatrans_acr_k)
}

#' @rdname evatransActual
#' @details
#' - **_AcceptPow**: only the potential ET 
#' is considered as th main factors for the ratio \mjseqn{f}.
#' \mjsdeqn{E_a = k  E_p^\gamma}
#' where
#'   - \mjseqn{k} is `param_evatrans_acp_k`
#'   - \mjseqn{\gamma} is `param_evatrans_acp_gamma`
#' @param param_evatrans_acp_k <0.1, 1> parameter for [evatransActual_AcceptPow()], ratio of this method
#' @param param_evatrans_acp_gamma <-3, 1> parameter for [evatransActual_AcceptPow()], exponent of this method
#' @export
evatransActual_AcceptPow <- function(atmos_potentialEvatrans_mm, water_mm, param_evatrans_acp_k, param_evatrans_acp_gamma) {
    .Call(`_EDCHM_evatransActual_AcceptPow`, atmos_potentialEvatrans_mm, water_mm, param_evatrans_acp_k, param_evatrans_acp_gamma)
}

#' @rdname evatransActual
#' @details
#' - **_VIC**: is similar with [evatransActual_SupplyPow()], estimate the water content in the storage.
#' \mjsdeqn{f = 1-\left(1-\frac{W}{C}\right)^{\gamma}}
#' where
#'   - \mjseqn{\gamma} is `param_evatrans_vic_gamma`
#' @param param_evatrans_vic_gamma <0.2, 5> parameter for [evatransActual_VIC()]
#' @export
evatransActual_VIC <- function(atmos_potentialEvatrans_mm, water_mm, capacity_mm, param_evatrans_vic_gamma) {
    .Call(`_EDCHM_evatransActual_VIC`, atmos_potentialEvatrans_mm, water_mm, capacity_mm, param_evatrans_vic_gamma)
}

#' @rdname evatransActual
#' @details
#' - **_GR4J**: is a little different than other method, it estimate not the ratio \mjseqn{f},
#' rather dieectly a equation with potential ET and water content.
#' And it need **no parameter**.
#' \mjsdeqn{E_a = \frac{W\left(2-\frac{W}{C}\right)\tanh \left(\frac{E_p}{C}\right)}{1 + \left(1-\frac{W}{C}\right)\tanh \left(\frac{E_p}{C}\right)}}
#' @export
evatransActual_GR4J <- function(atmos_potentialEvatrans_mm, capacity_mm, water_mm) {
    .Call(`_EDCHM_evatransActual_GR4J`, atmos_potentialEvatrans_mm, capacity_mm, water_mm)
}

#' @rdname evatransActual
#' @details
#' - **_UBC**: estimate the water content in the storage. 
#' (This is a little different than original, the parameter `P0AGEN` is replaced by \mjseqn{\frac{C}{\gamma}}.)
#' \mjsdeqn{f = 10^{\gamma \frac{W-C}{C}}}
#' where
#'   - \mjseqn{\gamma} is `param_evatrans_ubc_gamma`
#' @param param_evatrans_ubc_gamma <0.5, 2>parameter for [evatransActual_UBC()]
#' @export
evatransActual_UBC <- function(atmos_potentialEvatrans_mm, water_mm, capacity_mm, param_evatrans_ubc_gamma) {
    .Call(`_EDCHM_evatransActual_UBC`, atmos_potentialEvatrans_mm, water_mm, capacity_mm, param_evatrans_ubc_gamma)
}

#' @rdname evatransActual
#' 
#' @details
#' - **Land_Liang**: is also a similar method like [evatransActual_SupplyPow()], 
#' but it will estimate the supply ability agian, whwn the water is still not enough.
#' \mjsdeqn{E_l^* = \left(\frac{W}{C}\right)^\gamma E_p}
#' \mjsdeqn{E_l = \min \left(1, \frac{W}{E_l^*}\right) E_l^*}
#' where
#'   - \mjseqn{E_l^*} is the first estimated actuall ET
#'   - \mjseqn{E_l} is actuall ET from land, `land_evatrans_mm`
#'   - \mjseqn{\gamma} is `param_evatrans_lia_gamma`
#' @param param_evatrans_lia_gamma <0.4, 1> parameter for [evatransLand_Liang()]
#' @export
evatransLand_Liang <- function(atmos_potentialEvatrans_mm, water_mm, capacity_mm, param_evatrans_lia_gamma) {
    .Call(`_EDCHM_evatransLand_Liang`, atmos_potentialEvatrans_mm, water_mm, capacity_mm, param_evatrans_lia_gamma)
}

#' @rdname evatransActual
#' @details
#' - **Soil_Liang**: estimate the water content in the storage. 
#' (This is a little different than original, the parameter `P0AGEN` is replaced by \mjseqn{\frac{C}{\gamma}}.)
#' \mjsdeqn{f = \int_{0}^{A_{s}} d A + \int_{A_{s}}^{1} \frac{i_{0}}{i_{m} [1-(1-A)^{1 / B} ]} d A }
#' where
#'   - \mjseqn{B} is `param_evatrans_lia_B`
#' @param param_evatrans_lia_B <0.3, 2> parameter for [evatransSoil_Liang()]
#' @export
evatransSoil_Liang <- function(atmos_potentialEvatrans_mm, water_mm, capacity_mm, param_evatrans_lia_B) {
    .Call(`_EDCHM_evatransSoil_Liang`, atmos_potentialEvatrans_mm, water_mm, capacity_mm, param_evatrans_lia_B)
}

#' **infiltration**
#' @name infilt
#' @inheritParams all_vari
#' @param param_infilt_sur_k <0.01, 1> coefficient parameter for [infilt_SupplyRatio()]
#' @return infilt_mm (mm/m2) 
#' @export
infilt_SupplyRatio <- function(land_water_mm, soil_water_mm, soil_capacity_mm, param_infilt_sur_k) {
    .Call(`_EDCHM_infilt_SupplyRatio`, land_water_mm, soil_water_mm, soil_capacity_mm, param_infilt_sur_k)
}

#' @rdname infilt
#' @param param_infilt_sup_k <0.01, 1> coefficient parameter for [infilt_SupplyPow()]
#' @param param_infilt_sup_gamma parameters for [infilt_SupplyPow()]
#' @export
infilt_SupplyPow <- function(land_water_mm, soil_water_mm, soil_capacity_mm, param_infilt_sup_k, param_infilt_sup_gamma) {
    .Call(`_EDCHM_infilt_SupplyPow`, land_water_mm, soil_water_mm, soil_capacity_mm, param_infilt_sup_k, param_infilt_sup_gamma)
}

#' @rdname infilt
#' @param param_infilt_acr_k <0.01, 1> coefficient parameter for [infilt_AcceptRatio()]
#' @export
infilt_AcceptRatio <- function(land_water_mm, soil_water_mm, soil_capacity_mm, param_infilt_acr_k) {
    .Call(`_EDCHM_infilt_AcceptRatio`, land_water_mm, soil_water_mm, soil_capacity_mm, param_infilt_acr_k)
}

#' @rdname infilt
#' @param param_infilt_acp_k <0.01, 1> coefficient parameter for [infilt_AcceptPow()]
#' @param param_infilt_acp_gamma parameters for [infilt_AcceptPow()]
#' @export
infilt_AcceptPow <- function(land_water_mm, soil_water_mm, soil_capacity_mm, param_infilt_acp_k, param_infilt_acp_gamma) {
    .Call(`_EDCHM_infilt_AcceptPow`, land_water_mm, soil_water_mm, soil_capacity_mm, param_infilt_acp_k, param_infilt_acp_gamma)
}

#' @rdname infilt
#' @param param_infilt_hbv_beta parameters for [infilt_HBV()]
#' @export
infilt_HBV <- function(land_water_mm, soil_water_mm, soil_capacity_mm, param_infilt_hbv_beta) {
    .Call(`_EDCHM_infilt_HBV`, land_water_mm, soil_water_mm, soil_capacity_mm, param_infilt_hbv_beta)
}

#' @rdname infilt
#' @export
infilt_GR4J <- function(land_water_mm, soil_water_mm, soil_capacity_mm) {
    .Call(`_EDCHM_infilt_GR4J`, land_water_mm, soil_water_mm, soil_capacity_mm)
}

#' @rdname infilt
#' @param param_infilt_scs_CN parameters for [infilt_SCS()]
#' @export
infilt_SCS <- function(land_water_mm, soil_water_mm, soil_capacity_mm, param_infilt_scs_CN) {
    .Call(`_EDCHM_infilt_SCS`, land_water_mm, soil_water_mm, soil_capacity_mm, param_infilt_scs_CN)
}

#' @rdname infilt
#' @param land_impermeableFrac_1 the maximum impermeable fraction when th soil is fully saturated
#' @param param_infilt_ubc_P0AGEN <0.01, 1> coefficient parameter for [infilt_UBC()]
#' @export
infilt_UBC <- function(land_water_mm, land_impermeableFrac_1, soil_water_mm, soil_capacity_mm, param_infilt_ubc_P0AGEN) {
    .Call(`_EDCHM_infilt_UBC`, land_water_mm, land_impermeableFrac_1, soil_water_mm, soil_capacity_mm, param_infilt_ubc_P0AGEN)
}

#' @rdname infilt
#' @param param_infilt_xaj_B parameters for [infilt_XAJ()]
#' @export
infilt_XAJ <- function(land_water_mm, soil_water_mm, soil_capacity_mm, param_infilt_xaj_B) {
    .Call(`_EDCHM_infilt_XAJ`, land_water_mm, soil_water_mm, soil_capacity_mm, param_infilt_xaj_B)
}

#' **interception** water from land go into the soil.
#' @name intercep
#' @inheritParams all_vari
#' @return intercept_water_mm (mm/m2) intercepted water in this timestep
#' @export
intercep_Full <- function(atmos_rain_mm, land_interceptWater_mm, land_interceptCapacity_mm) {
    .Call(`_EDCHM_intercep_Full`, atmos_rain_mm, land_interceptWater_mm, land_interceptCapacity_mm)
}

#' **lateral flux**
#' @name lateral
#' @inheritParams all_vari
#' @param ground_lateralPotential_mm parameters
#' @return lateral_mm (mm/m2)
#' @export
lateral_GR4J <- function(ground_water_mm, ground_capacity_mm, ground_lateralPotential_mm) {
    .Call(`_EDCHM_lateral_GR4J`, ground_water_mm, ground_capacity_mm, ground_lateralPotential_mm)
}

#' @rdname lateral
#' @param param_lateral_grf_gamma parameters for [lateral_SupplyPow()]
#' @export
lateral_GR4Jfix <- function(ground_water_mm, ground_capacity_mm, ground_lateralPotential_mm, param_lateral_grf_gamma) {
    .Call(`_EDCHM_lateral_GR4Jfix`, ground_water_mm, ground_capacity_mm, ground_lateralPotential_mm, param_lateral_grf_gamma)
}

#' @rdname lateral
#' @param param_lateral_sur_k <0.01, 1> coefficient parameter for [lateral_SupplyRatio()]
#' @export
lateral_SupplyRatio <- function(ground_water_mm, ground_capacity_mm, param_lateral_sur_k) {
    .Call(`_EDCHM_lateral_SupplyRatio`, ground_water_mm, ground_capacity_mm, param_lateral_sur_k)
}

#' @rdname lateral
#' @param param_lateral_sup_k <0.01, 1> coefficient parameter for [lateral_SupplyPow()]
#' @param param_lateral_sup_gamma parameters for [lateral_SupplyPow()]
#' @export
lateral_SupplyPow <- function(ground_water_mm, ground_capacity_mm, param_lateral_sup_k, param_lateral_sup_gamma) {
    .Call(`_EDCHM_lateral_SupplyPow`, ground_water_mm, ground_capacity_mm, param_lateral_sup_k, param_lateral_sup_gamma)
}

#' **percolation**
#' @name percola
#' @inheritParams all_vari
#' @param param_percola_grf_k <0.01, 1> coefficient parameter for [percola_GR4Jfix()]
#' @return percola_mm (mm/m2)
#' @export
percola_GR4Jfix <- function(soil_water_mm, soil_capacity_mm, param_percola_grf_k) {
    .Call(`_EDCHM_percola_GR4Jfix`, soil_water_mm, soil_capacity_mm, param_percola_grf_k)
}

#' @rdname percola
#' @export
percola_GR4J <- function(soil_water_mm, soil_capacity_mm) {
    .Call(`_EDCHM_percola_GR4J`, soil_water_mm, soil_capacity_mm)
}

#' @rdname percola
#' @param param_percola_sur_k <0.01, 1> coefficient parameter for [percola_SupplyRatio()]
#' @export
percola_SupplyRatio <- function(soil_water_mm, param_percola_sur_k) {
    .Call(`_EDCHM_percola_SupplyRatio`, soil_water_mm, param_percola_sur_k)
}

#' @rdname percola
#' @param param_percola_sup_k <0.01, 1> coefficient parameter for [percola_SupplyPow()]
#' @param param_percola_sup_gamma parameters for [percola_SupplyPow()]
#' @export
percola_SupplyPow <- function(soil_water_mm, soil_capacity_mm, param_percola_sup_k, param_percola_sup_gamma) {
    .Call(`_EDCHM_percola_SupplyPow`, soil_water_mm, soil_capacity_mm, param_percola_sup_k, param_percola_sup_gamma)
}

#' **snow**
#' @name snow
#' @inheritParams all_vari
#' @param param_snow_kus_fE,param_snow_kus_fT parameters for [snowMelt_Kustas()]
#' @return snow_melt_mm (mm/m2) melted snow
#' @export
snowMelt_Kustas <- function(snow_ice_mm, atmos_temperature_Cel, atmos_netRadiat_MJ, param_snow_kus_fE, param_snow_kus_fT) {
    .Call(`_EDCHM_snowMelt_Kustas`, snow_ice_mm, atmos_temperature_Cel, atmos_netRadiat_MJ, param_snow_kus_fE, param_snow_kus_fT)
}

#' @rdname snow
#' @param param_snow_fac_Tmelt,param_snow_fac_Tb,param_snow_fac_f parameters for [snowMelt_Factor()]
#' @export
snowMelt_Factor <- function(snow_ice_mm, param_snow_fac_Tmelt, param_snow_fac_Tb, param_snow_fac_f) {
    .Call(`_EDCHM_snowMelt_Factor`, snow_ice_mm, param_snow_fac_Tmelt, param_snow_fac_Tb, param_snow_fac_f)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_EDCHM_RcppExport_registerCCallable', PACKAGE = 'EDCHM')
})
